[package]
name = "refraction-dispersion"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
after-effects = { git = "https://github.com/virtualritz/after-effects.git" }
rayon = "1"
cudarc = { version = "0.19", default-features = false, features = ["driver", "std", "fallback-dynamic-loading", "cuda-version-from-build-system"] }
bytemuck = { version = "1", features = ["derive"] }

[profile.release]
lto = "thin"
codegen-units = 1

[build-dependencies]
pipl = { git = "https://github.com/virtualritz/after-effects.git" }
