[package]
name = "lattice_lab_plugin"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
after-effects = { git = "https://github.com/virtualritz/after-effects.git" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
particlelab_engine_core = { path = "../particlelab_engine_core" }

[build-dependencies]
pipl = { git = "https://github.com/virtualritz/after-effects.git" }
